project = 'nbcollection'
copyright = '2020, adrn, eteq, jbcurtin'
author = 'adrian price-whelan, Erik Tollerud, Joe Curtin'
release = '0.1.0'
html_theme = "sphinx_rtd_theme"
master_doc = 'index'
extensions = []
templates_path = ['_templates']
exclude_patterns = []
html_static_path = ['_static']
